### ISSUE TITLE
Altitude measurement not preserved

### ISSUE THREAD

**Issue by CarlosCiruelos** [SylvainGa/crystal-face#4] opened 2022-04-15 21:11 UTC
The altitude measurement only holds on an FR55 watch face for about a minute. I can obtain a new GPS signal and the face will again display accurate altitude, but the measurement soon disappears again.

I have downloaded other watch faces such as Rails that preserve altitude. I prefer Crystal and I’m happy to help test and support your effort. 

Tested on Forerunner 55

**Comment by SylvainGa** [comment] 2022-04-16 13:03
Try the new version posted yesterday, It tries to keep the last known altitude in case of the watch is unable to retrieve it from barometric or GPS.

**Comment by CarlosCiruelos** [comment] 2022-04-16 14:43
Thank you. I tested it and the last known altitude is preserved, but only until any button is pressed. Then the measurement is lost again when returning to the watch screen. That’s sufficient for me and I truly appreciate your responsiveness - it may be something you wish to explore for the future. Thanks again and happy to help with any further testing.

**Comment by SylvainGa** [comment] 2022-04-17 01:32
So what you're saying is when the watch face loses focus, the known altitude is gone?

**Comment by CarlosCiruelos** [comment] 2022-04-17 01:45
Correct. Any button press or screen change causes the altitude to clear.  A new gps signal will replace and hold the altitude until the next screen change.

**Comment by SylvainGa** [comment] 2022-04-17 03:08
So following what it says under getElevationHistory for the supported devices, the Forerunner 55 has to rely on the activity to get the elevation since it doesn't keep track of elevation by itself, only through activity.
https://developer.garmin.com/connect-iq/api-docs/Toybox/SensorHistory.html

I'm thinking this last activity is not persistent. I added last time a global variable to hold the last activity altitude but that seems to not survive when the watch face loses focus. I coded it differently this time and if that was the case, the last know altitude should be preserved now.

Keep in mind that this altitude is taken for the last activity (through barometer or GPS), so if you move from that location, the altitude will not be valid until a new activity is started. At least, that's my understanding of it.

You should see a new version soon.

**Comment by CarlosCiruelos** [comment] 2022-04-17 03:32
Yes, I think your explanation of the “last activity” measurement makes sense - my previous watch (FR235) behaved similarly. I’ll keep an eye out for the new version. Take care and happy running.

**Comment by SylvainGa** [comment] 2022-04-17 03:34
Wait, I've goof. It might crash. I'm building a new one right now.

**Comment by SylvainGa** [comment] 2022-04-17 03:40
Ok, give this one a try

**Comment by CarlosCiruelos** [comment] 2022-04-17 04:30
I now crash (IQ! Error icon) when I add Altitude in any data field position (1, 2, or 3). All other settings function well and I can restore the watch face by removing Altitude.

**Comment by SylvainGa** [comment] 2022-04-17 04:40
When did you grab the app? I noticed after I uploaded it earlier tonight that I forgot a check for null (I can't reproduce what you're seeing in the simulator so it's not easy to debug). I added that check and re- uploaded the new version at 11:37 pm EDT (V2.7.3**.1**). Is it that one that is crashing? If so, can you send me the crash log? It's in the APP/LOGS directory of the watch itself when it's connected to a computer.

**Comment by CarlosCiruelos** [comment] 2022-04-17 16:15
I have now tested 2.7.3.1 through several focus loss use cases (button presses, notifications, calls). The last known GPS altitude is preserved!  Thank you very much. This is my watch face of choice and I’ve shared it with several friends. I appreciate all of your efforts.

**Comment by SylvainGa** [comment] 2022-04-17 16:55
I'm glad it's now resolved. I'll close this issue. Thanks for your help.

**Closed by SylvainGa** 2022-04-17 16:55 UTC
